version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
    - appnet
  data-loader:
    tty: true
    stdin_open: false
    networks:
    - appnet
    build:
      context: ./data-loader
    depends_on:
      - elasticsearch
    volumes:
      - ./data-loader:/opt/data-loader:z
    command: "node"
  frontend:
    networks:
    - appnet
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:z
    command: "yarn dev"
  backend:
    networks:
    - appnet
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app:z
      - ./dbdata:/opt/db:z
    environment:
      NODE_ENV: development
    command: "npx nodemon index.js"
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
